spring:
## ---------- Redis begin --------- ##
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
## ---------- Redis end ----------- ##
server:
  port: 443
  ssl:
    key-alias: ${SERVER_SSL_KEY_ALIAS}
    key-store: ${SERVER_SSL_KEY_STORE}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASS}
# --------- Telegram begin --------- #
telegram:
  bot:
    token: ${TG_BOT_TOKEN}
    webhook:
      enabled: ${TG_BOT_WEBHOOK_ENABLED}
      host: ${TG_BOT_HOST}
      certificate: ${TG_BOT_CERT}
      maxConnections: ${TG_BOT_MAX_CONNECTIONS}
# ---------- Telegram end ---------- #

#  PUT THIS ENVIRONMENT VARIABLES ON YOUR MACHINE
#
#  export TG_BOT_TOKEN=""
#  export TG_BOT_HOST=""
#  export TG_BOT_MAX_CONNECTIONS="100"
#  export REDIS_HOST="localhost"
#  export REDIS_PORT="6379"
#  export SERVER_SSL_KEY_ALIAS=""
#  export SERVER_SSL_KEY_STORE=""
#  export SERVER_SSL_KEY_STORE_PASS=""