spring:
## ---------- Redis begin --------- ##
  redis:
    host: localhost
    port: 6379
## ---------- Redis end ----------- ##
server:
  port: 80
# --------- Telegram begin --------- #
telegram:
  bot:
    token: ${TG_BOT_TOKEN}
# ---------- Telegram end ---------- #
